name: Learning Basics
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - name: Display version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      # - name: Run python programm
      #   run: python hello.py
      - name: Run Koans
        run: python ex1/contemplate_koans.py